### ISSUE TITLE
salve cannot to master

### ISSUE THREAD

**Issue by pranavpandey1998official** [alexanderfefelov/docker-mysql-replication#1]
I was using master's container name in MASTER_HOST param but slave cannot connect to master

**Comment by pranavpandey1998official** [comment]
ok If I use master's ip then it works, but don't work with master container name

**Comment by alexanderfefelov** [comment]
Instead of container name use container hostname. And update coniguration of your DNS server.

**Comment by pranavpandey1998official** [comment]
cool thanx
